#' @title Creates a Summary Datamatrix (XCMSnEXP objects)
#' @description creata a summary data matrix containing feature id, mz ,rt and
#'     intensity value detected for each feature.
#' @param x is a fillChromPeaks object
#' @param y indicates the type of response to be stored ('into', 'maxo')
#' @details peculiar of 'branch a', the function collates features information
#'     generated by the xcms featureDefinition() function with
#'     their corresponding response
#'     (either the integrated peak area or maximum intensity).
#'     The arguments of the function are the filled XCMSnEXP object and the type
#'     of instrumental response desired (either into or maxo).
#'     The data matrix is written into a.cdv file in the QC folder.
#' @export
#' @return Na
#' @seealso \code{\link[xcms]{XCMSnExp-class}}
#' @examples {data(xdata)
#'     dir.create("./QC")
#'     xdata <- groupChromPeaks(xdata,
#'         param = PeakDensityParam(sampleGroups = xdata$sample_group,
#'         minFraction = 0.3, bw = 20))
#'     xfilled <- fillChromPeaks(xdata, param =(FillChromPeaksParam(ppm = 50,
#'         expandMz = 0.5)))
#'     CreateDM(xfilled, 'maxo')
#'     }
CreateDM <- function(x, y) {
    ne <- 1
    envir = as.environment(ne)
    Feat_Def_DF <- data.frame(featureDefinitions(x))
    PKsFillInfo <- Feat_Def_DF[, (seq_along(Feat_Def_DF) - 1)]
    PKsFillValues <- as.matrix(featureValues(x, value = y))
    FilledPeakMat <- as.data.frame(cbind(PKsFillInfo, PKsFillValues))
    assign("FilledPeakMat", FilledPeakMat, ne)
    write.table(FilledPeakMat[with(FilledPeakMat,
            order(FilledPeakMat$rtmed, FilledPeakMat$mzmed)), ],
        file = "./QC/Filled_matrix.tsv", sep = "\t", quote = FALSE,
        col.names = NA)
}
