utils::globalVariables(c("BasePks", "BasePksCur",
    "ClassCol", "ClassType","classSize", "CPUs", "EICsMax", "Extra",
    "descriptive_stats", "Family","FilledPeakMat", "FWHMmax", "FWHMmin",
    "files", "filetype", "fitGauss","intThresh", "mzEnd", "mzErrAbs",
    "mzErrPpmMin", "mzErrPpmMax", "mzErrPpmMean","mzdifference", "mzMax",
    "mzPol", "mzStart", "mzref","minSam", "NormalizedMatrix","pathToProject","pl",
    "pl1","Plottype", "pd", "pwMin", "pwMax", "PMissing", "QCReps","rawfiles",
    "rtDelta", "rtEnd", "rtStart", "rtref", "MFeat", "fullDataSet",
    "testDataSet", "raw_refs", "raw_data", "Span", "SampleGroup", "selection",
    "sens", "set", "spn", "snThresh", "symbol", "tmp", "x_refs", "xsAlign",
    "xset", "minfrac", "dbw", "BSize", "MF", "xdata", "Sigma", "defbw",
    "Binsize","integ", "Defbw", "BinSize", "Intval", "Perfwhm",
    "corrthresh", "maxIso","ppmerror", "pvalue", "corexpth", "runtimeEnd",
    "runtimeStart", "runtime",'rawDataSet','xdata',"xSetRef", "bpSelection"))
